[[redirects]]
  from = "https://thedailydietitian.netlify.com"
  to = "https://www.thedailydietitian.co.uk"
  status = 301
  force = true

# Holding.
[[redirects]]
  from = "/"
  to = "/about"
  status = 302
