backend:
  name: git-gateway
publish_mode: editorial_workflow
media_folder: "src/site/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "recipes" # Used in routes, e.g., /admin/collections/blog
    label: "Recipes" # Used in the UI
    folder: "src/site/recipes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
