backend:
  name: git-gateway
publish_mode: editorial_workflow
media_folder: src/site/content/assets/uploads
public_folder: /assets/uploads
site_url: https://www.thedailydietitian.co.uk
collections:
  - name: recipes
    label: Recipes
    label_singular: Recipe
    description: Instructions for preparing a particular meal.
    folder: src/site/content/recipes
    create: true
    format: yaml-frontmatter
    slug: "{{ fields.slug }}"
    fields:
      - name: slug
        label: Slug
        widget: string
        hint: A unique URL fragment.
        pattern: ["^[a-z0-9-]+$", Must be a valid URL fragment.]
      - label: Permalink
        name: permalink
        widget: hidden
        default: /recipes/{{ slug }}/index.html
      - label: Layout
        name: layout
        widget: hidden
        default: recipe
      - label: Title
        name: title
        widget: string
      - label: Tags
        name: tags
        widget: hidden
        default: recipe
      - label: Body
        name: body
        widget: markdown
