---
label: Recipe
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- name: image
  type: file
  config:
    maxSize: '1'
  label: Image
  description: An enticing image.
- name: time_published
  type: datetime
  label: Date Published
  description: The date and time the recipe was published.
  config:
    required: true
    date_format: DD/MM/YYYY
    time_format: ''
    display_utc: false
  default: now
- name: type
  type: list
  config:
    use_select: true
    min: '1'
    max: '4'
    source:
      type: simple
    options:
    - Breakfast
    - Lunch
    - Dinner
    - Snack
  label: Type
  description: What type of meal is this?
