---
label: Recipe
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- name: image
  type: file
  config:
    maxSize: '1'
  label: Image
  description: An enticing image.
- name: time_published
  type: datetime
  label: Date Published
  description: The date and time the recipe was published.
  config:
    required: true
    date_format: DD/MM/YYYY
    time_format: ''
    display_utc: false
  default: now
- name: type
  type: list
  config:
    use_select: true
    min: '1'
    max: ''
    source:
      type: simple
    options:
    - Breakfast
    - Lunch
    - Dinner
    - Snack
  label: Type
- name: ingredients
  type: list
  config:
    use_select: false
    min: '1'
    max: 
  label: Ingredients
- name: nutrition_component
  type: list
  config:
    use_select: true
    min: '1'
    max: 
    source:
      type: simple
    options:
    - High Protein
    - Low Carb
  label: Nutrition Component
- name: dietary_preference
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: simple
    options:
    - Vegetarian
    - Vegan
    - Halal
  label: Dietary Preference
- name: allergens
  type: list
  config:
    use_select: true
    min: ''
    max: 
    source:
      type: simple
    options:
    - Egg
    - Dairy
  label: Allergens
- name: freezer_friendly
  type: boolean
  label: Freezer Friendly
  default: true
- name: batchable
  type: boolean
  label: Batchable
  description: Can this meal be batch-prepared?
pages:
- src/site/recipes/another-test.md
- src/site/recipes/test.md
