---
label: Recipe
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- name: image
  type: file
  config:
    maxSize: '1'
  label: Image
  description: An enticing image.
- name: time_published
  type: datetime
  label: Date Published
  description: The date and time the recipe was published.
  config:
    required: true
    date_format: DD/MM/YYYY
    time_format: ''
    display_utc: false
  default: now
- name: type
  type: select
  default: Dinner
  config:
    required: true
    options:
    - Breakfast
    - Lunch
    - Dinner
    - Snack
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
